---
server:
  port: 8014

ecos:
  webapp:
    x509:
      keys:
        application:
          location: classpath:ecos/x509/keys/application.key
  job:
    time-tracking:
      resetRemainingTimeAndStartSla:
        cron: '0 0 0 1 * *'
